# Generated by Django 4.2.7 on 2024-03-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
