# Generated by Django 4.2.7 on 2024-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежа на stripe'),
        ),
    ]
