# Generated by Django 4.2.7 on 2024-03-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_stripe_id_payment_stripe_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка для платежа'),
        ),
    ]
