# Generated by Django 4.2.7 on 2024-03-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_payment_stripe_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка для платежа'),
        ),
    ]
